"""
Problem 12 - Highly divisible triangular number


The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""


def count_divisors(n):
    factors = prime_factors(n)
    divisors = 1
    for k in factors:
        divisors *= factors[k] + 1
    return divisors


def prime_factors(n):
    current = 2
    factors = {}
    while n > 1:
        if n % current == 0:
            if current in factors.keys():
                factors[current] += 1
            else:
                factors[current] = 1
            n /= current
        else:
            current += 1
    return factors


i = 1
current_triangle = 1
while True:
    if count_divisors(current_triangle) > 500:
        break
    i += 1
    current_triangle += i
print(current_triangle)
